/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/user": {
    get: operations["UserController_findAll"];
  };
  "/auth/sign-in": {
    post: operations["AuthController_signIn"];
  };
  "/auth/sign-up": {
    post: operations["AuthController_signUp"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SigInputDto: {
      email: string;
      password: string;
    };
    SignInDto: {
      accessToken: string;
    };
    CreateAccountInputDto: {
      email: string;
      password: string;
      firstName: string;
      lastName: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_getHello: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_signIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SigInputDto"];
      };
    };
    responses: {
      /** @description Sign in */
      200: {
        content: {
          "application/json": components["schemas"]["SignInDto"];
        };
      };
    };
  };
  AuthController_signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountInputDto"];
      };
    };
    responses: {
      /** @description Sign in */
      200: {
        content: {
          "application/json": components["schemas"]["SignInDto"];
        };
      };
    };
  };
}
